"""Initial spec-aligned schema (scan_jobs, scan_results, exploit_correlations)

Revision ID: 6c8543930863
Revises: 
Create Date: 2026-05-20 01:49:09.181365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8543930863'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_jobs',
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('selected_modules', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('scan_id')
    )
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_jobs_target'), ['target'], unique=False)

    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=50), nullable=True),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('cve_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_jobs.scan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_results_cve_id'), ['cve_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_results_scan_id'), ['scan_id'], unique=False)

    op.create_table('exploit_correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('exploit_title', sa.String(length=255), nullable=False),
    sa.Column('exploit_id', sa.String(length=40), nullable=True),
    sa.Column('exploit_path', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['scan_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exploit_correlations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exploit_correlations_result_id'), ['result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exploit_correlations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exploit_correlations_result_id'))

    op.drop_table('exploit_correlations')
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_results_scan_id'))
        batch_op.drop_index(batch_op.f('ix_scan_results_cve_id'))

    op.drop_table('scan_results')
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_jobs_target'))

    op.drop_table('scan_jobs')
    # ### end Alembic commands ###
