"""Add product+version columns to scan_results

Revision ID: c23464e46085
Revises: 6c8543930863
Create Date: 2026-05-20 02:05:43.002062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23464e46085'
down_revision = '6c8543930863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_scan_results_product'), ['product'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_results_product'))
        batch_op.drop_column('version')
        batch_op.drop_column('product')

    # ### end Alembic commands ###
