"""Add target_port + target_scheme columns to scan_jobs

Revision ID: e213856201a4
Revises: c23464e46085
Create Date: 2026-06-04 00:34:09.667364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e213856201a4'
down_revision = 'c23464e46085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_scheme', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_column('target_scheme')
        batch_op.drop_column('target_port')

    # ### end Alembic commands ###
